image: golang:1.9.3

# variables:

stages:
  - build
  - test
  - deploy

before_script:
    - mkdir -p $GOPATH/src/github.com
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/github.com/kradalby/terraform-provider-vcd
    - cd $GOPATH/src/github.com/kradalby/terraform-provider-vcd
    - bash scripts/gogetcookie.sh
      #    - go get github.com/kardianos/govendor
      #    - go get github.com/jinzhu/copier

build:
  stage: build
  script:
      - make build
      - cp -r bin $CI_PROJECT_DIR/.
  artifacts:
      paths:
          - ./bin/terraform-provider-vcd-linux-amd64
          - ./bin/terraform-provider-vcd-freebsd-amd64
          - ./bin/terraform-provider-vcd-darwin-amd64
          - ./bin/terraform-provider-vcd-win-amd64.exe

test:
  stage: test
  script:
      - export "VCD_USER=$VCD_USER"
      - export "VCD_PASSWORD=$VCD_PASSWORD"
      - export "VCD_ORG=$VCD_ORG"
      - export "VCD_URL=$VCD_URL"
      - export "VCD_VDC=$VCD_VDC"
      - export "VCD_MAX_RETRY_TIMEOUT=3000"
      - export "VCD_ALLOW_UNVERIFIED_SSL=true"
      - export "VCD_EDGE_GATEWAY=derp"

      - make testacc

pages:
    stage: deploy
    script:
      - cp bin/terraform-provider-vcd-linux-amd64 public/. 
      - cp bin/terraform-provider-vcd-freebsd-amd64 public/. 
      - cp bin/terraform-provider-vcd-darwin-amd64 public/. 
      - cp bin/terraform-provider-vcd-win-amd64.exe public/. 
    artifacts:
      paths:
        - public


